WebApplication12/Controllers/FeedbackController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplication12.Models;


namespace WebApplication12.Controllers {
    public class FeedbackController : Controller{
        /// <summary>
        ///  Метод, возвращающий страницу с отзывами
        /// </summary>
        [HttpGet]
        public IActionResult Add () {
            return View();
        }

        /// <summary>
        /// Метод для Ajax-запросов
        /// </summary>
        [HttpPost]
        public IActionResult Add (Feedback feedback) {
            return StatusCode(200, $"{feedback.From}, спасибо за отзыв!");
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error () {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

WebApplication12/Controllers/RequestController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using WebApplication12.Models;
using WebApplication12.Models.DB;
using WebApplication12.Models.Repositories;

namespace WebApplication12.Controllers {
    public class RequestController :Controller{
        private readonly ILogsRepositories _repo;
        private readonly ILogger<RequestController> _logger;

        // Также добавим инициализацию в конструктор
        public RequestController (ILogger<RequestController> logger, ILogsRepositories repo) {
            _logger = logger;
            _repo = repo;
        }
        public async Task<IActionResult> Index () {
            var authors = await _repo.GetLogs();
            return View(authors);
        }
        [HttpPost]
        public async Task<IActionResult> Log (Request request) {
            request.Date = DateTime.Now;
            request.Url = " ";
            await _repo.AddLogs(request);
            return View(request);
        }
        [HttpGet]
        public IActionResult Log () {
            return View();
        }
    }
}

WebApplication12/Controllers/UsersController.cs
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;
using WebApplication12.Models.DB;
using WebApplication12.Models.Repositories;

namespace WebApplication12.Controllers {
    public class UsersController : Controller {
        private readonly IBlogRepository _repo;
      
       public UsersController(IBlogRepository repo)
       {
           _repo = repo;
       }
      
       public async Task <IActionResult> Index()
       {
           var authors = await _repo.GetUsers();
           return View(authors);
       }
        public async Task<IActionResult> Authors () {
            var authors = await _repo.GetUsers();
            return View(authors);
        }
        [HttpPost]
        public async Task<IActionResult> Register (User newUser) {
            await _repo.AddUser(newUser);
            return View(newUser);
        }
        [HttpGet]
        public IActionResult Register () {
            return View();
        }
    }
}

WebApplication12/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - WebApplication12</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">WebApplication12</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Users" asp-action="Register">Register</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Feedback" asp-action="Add">Contact us</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Request" asp-action="index">logs</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - WebApplication12 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>